sms:
  smpp:
    url: http://196.188.172.191:13013/cgi-bin/sendsms
    username: admin
    password: Gateway9409
    charset:
    coding:
    ipAddress: 196.188.172.191
slack:
  webhook-url: https://hooks.slack.com/services/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

  #102.218.49.24 RayMIF RayMIF12
server:
  port: 8089

spring:
  datasource:
    url: jdbc:sqlserver://172.16.1.53:53512;databaseName=test_hosny;encrypt=true;trustServerCertificate=true;andtrustServerCertificate=false
    username: sa
    password: Today1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  #    show-sql: true
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 25
logging:
  pattern:
    file: '%date| %-5level | %-30thread | hudhud-sms-gateway | %-30.30logger{0} -%line
      |%msg%n'
    console: '%date| %highlight(%-5level) | %magenta(%-30thread) | hudhud-sms-gateway
      | %-30.30logger{0} -%line |%msg%n'
  file:
    path: E:\services\SMS-GATEWAY-PROD\logs
    name: ${logging.file.path}/sms-gateway-log.log